### ISSUE TITLE
图片缺失

### ISSUE THREAD

**Issue by wang-zerui** [marsCatXdu/MyCompilePrincipleNote#1]
https://github.com/marsCatXdu/MyCompilePrincipleNote/blob/030e2aa9cb116a0d9b6cde2b7d08f7dc16625bd8/%E7%BC%96%E8%AF%91%E5%8E%9F%E7%90%86%E7%AC%94%E8%AE%B012%EF%BC%9A%E8%87%AA%E4%B8%8A%E8%80%8C%E4%B8%8B%E8%AF%AD%E6%B3%95%E5%88%86%E6%9E%90%EF%BC%882%EF%BC%89%E9%9D%9E%E9%80%92%E5%BD%92%E9%A2%84%E6%B5%8B%E5%88%86%E6%9E%90%E5%99%A8%E3%80%81FIRST%20%26%20FOLLOW%20%E9%9B%86%E5%90%88%E8%AE%A1%E7%AE%97.md?plain=1#L7

No image here.

学长好 正在结合您的笔记学习，帮助很大！但是这里有图缺失，不知道您是否有空改一下。

**Comment by marsCatXdu** [comment]
> https://github.com/marsCatXdu/MyCompilePrincipleNote/blob/030e2aa9cb116a0d9b6cde2b7d08f7dc16625bd8/%E7%BC%96%E8%AF%91%E5%8E%9F%E7%90%86%E7%AC%94%E8%AE%B012%EF%BC%9A%E8%87%AA%E4%B8%8A%E8%80%8C%E4%B8%8B%E8%AF%AD%E6%B3%95%E5%88%86%E6%9E%90%EF%BC%882%EF%BC%89%E9%9D%9E%E9%80%92%E5%BD%92%E9%A2%84%E6%B5%8B%E5%88%86%E6%9E%90%E5%99%A8%E3%80%81FIRST%20%26%20FOLLOW%20%E9%9B%86%E5%90%88%E8%AE%A1%E7%AE%97.md?plain=1#L7
> 
> No image here.
> 
> 学长好 正在结合您的笔记学习，帮助很大！但是这里有图缺失，不知道您是否有空改一下。

不好意思，刚看到消息
可以先在我的 juejin 博客查看，图片我要找时间再补
https://juejin.cn/post/6854573208583012360

**Comment by wang-zerui** [comment]
好的 感谢
